language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.9"
# command to install dependencies
install:
  - pip install -r api/requirements.txt
# command to run tests
script:
  - python api/src/manage.py test